// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nedtdgosmeodivubjfgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lZHRkZ29zbWVvZGl2dWJqZmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDE2MjksImV4cCI6MjA2NDAxNzYyOX0.TzVWlYHpIptEsJ69v3fvNQ3g5DGo2AKE3xJ2s4sPSds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);